import { useMemo } from 'react'
import { renderSVG } from 'uqr'

/**
 * A QR code for the room link, rendered as inline SVG (bundled, no network). Kept dark
 * modules on white — contrast is what makes it scan reliably, so we don't theme the
 * modules themselves; the white card sits inside a rounded container in ShareContent.
 */
export function QRCode({ value, className }: { value: string; className?: string }) {
  const svg = useMemo(
    () => renderSVG(value, { border: 1, blackColor: '#14110f', whiteColor: '#ffffff' }),
    [value],
  )

  return (
    <div
      role="img"
      aria-label="QR code to join the room"
      className={className}
      // Content is generated by uqr from our own URL — no untrusted input.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}
